default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_original

development:
  <<: *default
  
production:
  <<: *default
  host: Connection の Hostname
  database: Connection の Database
  username: Connection の Username
  password: Connection の Password