development:
  adapter: postgresql
  encoding: unicode
  database: s_original

production:
  adapter: postgresql
  encoding: unicode
  database: s_original_xjxo
  host: dpg-d09i10p5pdvs73dnttg0-a
  username: s_original_xjxo_user
  password: 2bOBqYMGQYSQB74NABlN3QqVnwNaodjF
