development:
  adapter: postgresql
  encoding: unicode
  database: s_original

production:
  adapter: postgresql
  encoding: unicode
  database: s_original_27yl
  host: dpg-d09l6m3e5dus73bpqnq0-a
  username: s_original_27yl_user
  password: heNTN2O5YFry6PgIKSF9GFkeNFkFJe8C

default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_form
