default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_original

development:
  <<: *default
  
production:
  <<: *default
  host: dpg-d093u949c44c73adh9dg-a
  database: s_original_435w
  username: s_original_435w_user
  password: jQVef20TDQNWqzEr1qHm6zoyMltlmcnt