default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_original

development:
  <<: *default
  
production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>